import { z } from "zod";

export const createBriefSchema = z.object({
  requestId: z
    .string({
      message: "Request ID is required",
    })
    .uuid({ message: "Invalid request ID format" }),
});

// Validates brief generated by OpenAI
export const briefResultSchema = z.object({
  productOverview: z
    .string({
      message: "Product overview is required",
    })
    .min(10, "Product overview must be at least 10 characters")
    .max(2000, "Product overview must not exceed 2000 characters"),
  
  confirmedRequirements: z
    .array(
      z.string().min(1, "Requirement cannot be empty")
    )
    .min(1, "At least one requirement must be confirmed")
    .max(50, "Too many requirements"),
  
  assumptions: z
    .array(
      z.string().min(1, "Assumption cannot be empty")
    )
    .min(0)
    .max(50, "Too many assumptions"),
  
  openQuestions: z
    .array(
      z.string().min(1, "Question cannot be empty")
    )
    .min(0)
    .max(50, "Too many questions"),
  
  procurementSummary: z
    .string({
      message: "Procurement summary is required",
    })
    .min(20, "Procurement summary must be at least 20 characters")
    .max(5000, "Procurement summary must not exceed 5000 characters"),
});

export type CreateBriefInput = z.infer<typeof createBriefSchema>;
export type BriefResultValidated = z.infer<typeof briefResultSchema>;
