import { z } from "zod";

export const createBriefSchema = z.object({
  requestId: z.string().uuid("Invalid request ID format"),
});

// Validates brief generated by OpenAI
export const briefResultSchema = z.object({
  productOverview: z.string().min(10, "Product overview must be at least 10 characters"),
  confirmedRequirements: z.array(z.string().min(1)),
  assumptions: z.array(z.string().min(1)),
  openQuestions: z.array(z.string().min(1)),
  procurementSummary: z.string().min(20, "Procurement summary must be at least 20 characters"),
});

export type CreateBriefInput = z.infer<typeof createBriefSchema>;
export type BriefResultValidated = z.infer<typeof briefResultSchema>;
